name: rest_thoughts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - absl-py
  - tensorflow=2.12  # can adjust depending on GPU/CPU and CUDA setup
  - pip
  - pip:
      - tensorflow-hub