name: rest_thoughts_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - imbalanced-learn
  - absl-py
  - tensorflow
  - pip
  - pip:
      - tensorflow-hub